package Site::Portfolio::Model::PortfolioDb;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Site::Portfolio::Schema::PortfolioDb',
    rows => 12,
#     connect_info => {
#         dsn => 'dbi:mysql:PhotoGalleryDB',
#         user => 'pg',
#         password => '4rtyuehe',
#     }
);

=head1 NAME

Site::Portfolio::Model::PortfolioDb - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Site::Portfolio>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Site::Portfolio::Schema::PortfolioDb>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Pavel Yefimov

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

http://brainbuz.org/techinfo/Catalyst-Model-Simple-Tutorial.html

=cut

1;
